# Secret Manager secrets for NPA publisher registration tokens.
#
# Each publisher gets its own secret. The secret version stores the single-use
# registration token generated by Netskope. The VM startup script fetches this
# token using its service account identity (via the GCP metadata server) and
# passes it to npa_publisher_wizard. After registration the token is exhausted.
#
# To re-register a publisher (e.g. after a failed boot):
#   terraform apply \
#     -replace='netskope_npa_publisher_token.this["KEY"]' \
#     -replace='google_secret_manager_secret_version.publisher_token["KEY"]'
# Then reset the VM: gcloud compute instances reset NAME --zone ZONE

resource "google_secret_manager_secret" "publisher_token" {
  for_each  = local.publishers
  secret_id = "${each.value.name}-registration-token"
  project   = var.gcp_project_id
  labels    = local.common_labels

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "publisher_token" {
  for_each    = local.publishers
  secret      = google_secret_manager_secret.publisher_token[each.key].id
  secret_data = netskope_npa_publisher_token.this[each.key].token
}
